export enum FilterKeys {
    PAGE = "page",
    LIMIT = "limit",
    NAME = "name",
    SORT_BY = "sortBy",
    CREATED_BEFORE = "createdBefore",
    CREATED_AFTER = "createdAfter",
    PRICE_MIN = "priceMin",
    PRICE_MAX = "priceMax",
    MATERIAL_IDS = "materialIds",
    COLOR_IDS = "colorIds",
    PACK_IDS = "packIds",
    HARDNESS = "hardness",
    TYPE = "type",
    INTENSITY = "intensity",
}
